module.exports = {
    vuturaLoginPage: "https://app.vutura.io/signIn",
    homePage: "https://app.vutura.io/bot",
    accountPage: "https://app.vutura.io/account",
    planPage: "https://app.vutura.io/plan",
    movePathPage: "https://app.vutura.io/path",
    botHomePage: "https://app.vutura.io/statisticVutura",
    qnaPage: "https://app.vutura.io/qna",
    broadcastPage: "https://app.vutura.io/broadcast",
    pathPage: "https://app.vutura.io/path",
    vuturaLoginPageCi: "https://staging-dashboard.vutura.io/signIn",
    botPage: "https://dashboard-staging.vutura.io/bot",
    statisticPage: "https://dashboard-staging.vutura.io/qna",
    exportToPDFPage: "https://dashboard-staging.vutura.io/statisticVutura",
    buildPage: "https://dashboard-staging.vutura.io/qna",
    AddNewQnaPage: "https://dashboard-staging.vutura.io/qna",
    answerpage: "https://dashboard-staging.vutura.io/qna",
    textpage: "https://dashboard-staging.vutura.io/qna",
    savepage: "https://dashboard-staging.vutura.io/qna",
    okpage: "https://dashboard-staging.vutura.io/qna",
    UploadImagePage: "https://dashboard-staging.vutura.io/path",
    botPageVue: "https://app.vutura.io/bot",
    vuturaLoginPageVue: "https://app.vutura.io/signIn"
}